[colors]
bg = "#222436"
bg_dark = "#1e2030"
bg_highlight = "#2f334d"
black = "#1b1d2b"
fg = "#c8d3f5"
fg_dark = "#828bb8"
fg_gutter = "#3b4261"
comment = "#636da6"
blue = "#82aaff"
green = "#c3e88d"
border_highlight = "#589ed7"
magenta = "#c099ff"
yellow = "#ffc777"

[ui]
text = "fg"
text_dim = "fg_dark"
text_muted = "fg_gutter"
author = "magenta"
highlight = "yellow"
link = "blue"
date = "green"
border = "fg_gutter"
selection = "bg_highlight"
popup_bg = "bg_dark"
popup_border = "border_highlight"
normal_bg = "blue"
insert_bg = "green"
status_fg = "black"
